---
version: '3'
services:

# START SERVICE confluent_cc.sasl
  controlcenter:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.confluent_cc.sasl:5.4.0
    environment: ['CONTROL_CENTER_REPLICATION_FACTOR=3','CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_REPLICATION=3','CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION=3','CONTROL_CENTER_COMMAND_TOPIC_REPLICATION=3','CONTROL_CENTER_METRICS_TOPIC_REPLICATION=3','CONFLUENT_METRICS_TOPIC_REPLICATION=3','CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS=3','CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1','CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1','CONTROL_CENTER_METRICS_TOPIC_MAX_MESSAGE_BYTES=8388608','CONTROL_CENTER_BOOTSTRAP_SERVERS=${CONFLUENT_CC_SASL_ENVIRONMENT_BOOTSTRAP_SERVERS}','CONTROL_CENTER_STREAMS_SECURITY_PROTOCOL=SASL_SSL','CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${CONFLUENT_CC_SASL_ENVIRONMENT_STREAMS_API_KEY}" password="${CONFLUENT_CC_SASL_ENVIRONMENT_STREAMS_API_SECRET}";','CONTROL_CENTER_STREAMS_SASL_MECHANISM=PLAIN','CONTROL_CENTER_STREAMS_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=https','CONTROL_CENTER_SCHEMA_REGISTRY_URL=${CONFLUENT_CC_SASL_ENVIRONMENT_SCHEMA_REGISTRY_URL}','CONTROL_CENTER_SCHEMA_REGISTRY_BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO','CONTROL_CENTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO=${CONFLUENT_CC_SASL_ENVIRONMENT_SCHEMA_REGISTRY_API_KEY}:${CONFLUENT_CC_SASL_ENVIRONMENT_SCHEMA_REGISTRY_API_SECRET}','CONTROL_CENTER_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL=SASL_SSL','CONTROL_CENTER_MONITORING_INTERCEPTOR_SASL_MECHANISM=PLAIN','CONTROL_CENTER_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="<api-key>" password="<api-secret>";','CONTROL_CENTER_MONITORING_INTERCEPTOR_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=https','CONTROL_CENTER_CONNECT_CLUSTER=${CONFLUENT_CC_SASL_KAFKA_CONNECT}','CONTROL_CENTER_CONNECT_CLUSTER_BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO','CONTROL_CENTER_CONNECT_CLUSTER_BASIC_AUTH_USER_INFO=${CONFLUENT_CC_SASL_ENVIRONMENT_CONNECT_CLUSTER_API_KEY}:${CONFLUENT_CC_SASL_ENVIRONMENT_CONNECT_CLUSTER_API_SECRET}','CONTROL_CENTER_KSQL_KSQLDB1_URL=${CONFLUENT_CC_SASL_ENVIRONMENT_KSQL_URL}','CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL=${CONFLUENT_CC_SASL_ENVIRONMENT_KSQL_ADVERTISED_URL}','CONTROL_CENTER_KSQL_KSQLDB1_BASIC_AUTH_CREDENTIALS_SOURCE=USER_INFO','CONTROL_CENTER_KSQL_KSQLDB1_BASIC_AUTH_USER_INFO=${CONFLUENT_CC_SASL_ENVIRONMENT_KSQL_API_KEY}:${CONFLUENT_CC_SASL_ENVIRONMENT_KSQL_API_SECRET}']
    command: []
    volumes: []
    ports: [${CONFLUENT_CC_SASL_PORTS}]
    networks: [package_overlay]
    deploy:
      mode: replicated
      replicas: ${CONFLUENT_CC_SASL_DEPLOY_REPLICAS}
      resources:
        limits:
          cpus: '${CONFLUENT_CC_SASL_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${CONFLUENT_CC_SASL_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${CONFLUENT_CC_SASL_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${CONFLUENT_CC_SASL_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${CONFLUENT_CC_SASL_DEPLOY_PLACEMENT_CONSTRAINTS}]
      labels: [${CONFLUENT_CC_SASL_DEPLOY_LABELS}]
    labels: [${CONFLUENT_CC_SASL_LABELS}]
# END SERVICE confluent_cc.sasl

volumes: {}
networks: {package_overlay: { external: true }}
